[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
